spring:
  application:
    name: order-api
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
    virtual-host: /
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10
      queue:
        order-items:
          durable: true
          auto-delete: false
          exclusive: false